version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 27000:27017
  springboot-jwt-mongo-demo:
    image: springboot-jwt-mongo-demo:latest
    container_name: springboot-jwt-mongo-demo
    ports:
      - 8090:8090
    links:
      - mongodb